// Code generated by RockMem. DO NOT EDIT.
package ecs

import (
	"errors"
	"fmt"
	rockmem "github.com/zllangct/rockmem/golang"
	"unsafe"
)

var _ unsafe.Pointer
var _ = errors.New("")
var _ fmt.State

var _Null_ecs = [117]byte{}
var _NullReader_ecs = rockmem.NewReader(_Null_ecs[:])

func init() {
}

const (
	PacketIdentifierSerializableUSetData              = 14494556342195307757
	PacketIdentifierSerializableSparseArrayData       = 16579480448794251260
	PacketIdentifierSerializableEntitySetData         = 9549003896643909816
	PacketIdentifierSerializableEntityIDGeneratorData = 13239573087695456737
	PacketIdentifierSerializableComponentSetEntry     = 5342222988257397387
	PacketIdentifierSerializableWorldData             = 11535273365904318300
)

// SerializableUSetData USet serializable data structure
// SerializableUSetData Used for serializing USet[T] container, stores raw bytes of elements
type SerializableUSetData struct {
	EleSize  uint64 // Size of each element
	Len      int64  // Number of elements
	InitSize int64  // Initial capacity
	Data     []byte // Raw bytes of all elements
}

// NewSerializableUSetData creates a new SerializableUSetData instance
func NewSerializableUSetData() *SerializableUSetData {
	return &SerializableUSetData{}
}

// PacketIdentifier returns the unique identifier for SerializableUSetData
func (x *SerializableUSetData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableUSetData
}

// Reset resets all fields to their default values
func (x *SerializableUSetData) Reset() {
	x.Read((*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableUSetData as root object to the writer
func (x *SerializableUSetData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableUSetData to the writer at the specified offset
func (x *SerializableUSetData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(44)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__EleSizeOffset := offset + 4
	writer.Write8At(__EleSizeOffset, *(*uint64)(unsafe.Pointer(&x.EleSize)))
	__LenOffset := offset + 12
	writer.Write8At(__LenOffset, *(*uint64)(unsafe.Pointer(&x.Len)))
	__InitSizeOffset := offset + 20
	writer.Write8At(__InitSizeOffset, *(*uint64)(unsafe.Pointer(&x.InitSize)))
	__DataSize := uint(1 * len(x.Data))
	__DataCap := __DataSize
	__DataOffset, err := writer.Alloc(__DataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+28+0, uint32(__DataOffset))
	writer.Write4At(offset+28+4, uint32(__DataSize))
	writer.Write4At(offset+28+8, uint32(__DataCap))
	writer.Write4At(offset+28+12, uint32(1))
	if len(x.Data) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Data: len=%d, size=%d\n", len(x.Data), __DataSize)
		}
		writer.WriteAt(__DataOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Data[0])), __DataSize))
	}

	return offset, nil
}

// WriteDefault writes the SerializableUSetData default value to the writer at the specified offset
func (x *SerializableUSetData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(44)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *SerializableUSetData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableUSetDataViewer(reader, 0), reader)
}

func (x *SerializableUSetData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableUSetDataViewer(reader, offset), reader)
}

func (x *SerializableUSetData) Read(viewer *SerializableUSetDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.EleSize = viewer.EleSize()
	x.Len = viewer.Len()
	x.InitSize = viewer.InitSize()
	x.Data = viewer.Data(reader)
}

// SerializableSparseArrayData SparseArray serializable data structure
// SerializableSparseArrayData Used for serializing SparseArray[K, V] container
type SerializableSparseArrayData struct {
	USetData        SerializableUSetData // Embedded USet data
	Indices         []int32              // Sparse index mapping
	Idx2Key         []int32              // Dense index to key mapping
	MaxKey          int64                // Maximum key value
	ShrinkThreshold int32                // Shrink threshold
	InitSize        int32                // Initial size
	IsKOrder        bool                 // Is key-ordered
}

// NewSerializableSparseArrayData creates a new SerializableSparseArrayData instance
func NewSerializableSparseArrayData() *SerializableSparseArrayData {
	return &SerializableSparseArrayData{}
}

// PacketIdentifier returns the unique identifier for SerializableSparseArrayData
func (x *SerializableSparseArrayData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableSparseArrayData
}

// Reset resets all fields to their default values
func (x *SerializableSparseArrayData) Reset() {
	x.Read((*SerializableSparseArrayDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableSparseArrayData as root object to the writer
func (x *SerializableSparseArrayData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableSparseArrayData to the writer at the specified offset
func (x *SerializableSparseArrayData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(57)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__USetDataSize := uint(44)
	__USetDataOffset, err := writer.Alloc(__USetDataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4, uint32(__USetDataOffset))
	if _, err := x.USetData.Write(writer, __USetDataOffset); err != nil {
		return offset, err
	}
	__IndicesSize := uint(4 * len(x.Indices))
	__IndicesCap := __IndicesSize
	__IndicesOffset, err := writer.Alloc(__IndicesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+8+0, uint32(__IndicesOffset))
	writer.Write4At(offset+8+4, uint32(__IndicesSize))
	writer.Write4At(offset+8+8, uint32(__IndicesCap))
	writer.Write4At(offset+8+12, uint32(4))
	if len(x.Indices) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Indices: len=%d, size=%d\n", len(x.Indices), __IndicesSize)
		}
		writer.WriteAt(__IndicesOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Indices[0])), __IndicesSize))
	}
	__Idx2KeySize := uint(4 * len(x.Idx2Key))
	__Idx2KeyCap := __Idx2KeySize
	__Idx2KeyOffset, err := writer.Alloc(__Idx2KeySize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+24+0, uint32(__Idx2KeyOffset))
	writer.Write4At(offset+24+4, uint32(__Idx2KeySize))
	writer.Write4At(offset+24+8, uint32(__Idx2KeyCap))
	writer.Write4At(offset+24+12, uint32(4))
	if len(x.Idx2Key) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Idx2Key: len=%d, size=%d\n", len(x.Idx2Key), __Idx2KeySize)
		}
		writer.WriteAt(__Idx2KeyOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Idx2Key[0])), __Idx2KeySize))
	}
	__MaxKeyOffset := offset + 40
	writer.Write8At(__MaxKeyOffset, *(*uint64)(unsafe.Pointer(&x.MaxKey)))
	__ShrinkThresholdOffset := offset + 48
	writer.Write4At(__ShrinkThresholdOffset, *(*uint32)(unsafe.Pointer(&x.ShrinkThreshold)))
	__InitSizeOffset := offset + 52
	writer.Write4At(__InitSizeOffset, *(*uint32)(unsafe.Pointer(&x.InitSize)))
	__IsKOrderOffset := offset + 56
	writer.Write1At(__IsKOrderOffset, *(*uint8)(unsafe.Pointer(&x.IsKOrder)))

	return offset, nil
}

// WriteDefault writes the SerializableSparseArrayData default value to the writer at the specified offset
func (x *SerializableSparseArrayData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(57)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__USetDataSize := uint(44)
	__USetDataOffset, err := writer.Alloc(__USetDataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4, uint32(__USetDataOffset))
	if _, err := x.USetData.WriteDefault(writer, __USetDataOffset); err != nil {
		return offset, err
	}

	return offset, nil
}

func (x *SerializableSparseArrayData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableSparseArrayDataViewer(reader, 0), reader)
}

func (x *SerializableSparseArrayData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableSparseArrayDataViewer(reader, offset), reader)
}

func (x *SerializableSparseArrayData) Read(viewer *SerializableSparseArrayDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.USetData.Read(viewer.USetData(reader), reader)
	x.Indices = viewer.Indices(reader)
	x.Idx2Key = viewer.Idx2Key(reader)
	x.MaxKey = viewer.MaxKey()
	x.ShrinkThreshold = viewer.ShrinkThreshold()
	x.InitSize = viewer.InitSize()
	x.IsKOrder = viewer.IsKOrder()
}

// SerializableEntitySetData EntitySet serializable data structure
// SerializableEntitySetData Flattened representation for serializing EntitySet
// SerializableEntitySetData EntityInfos are stored as parallel arrays for efficient serialization
type SerializableEntitySetData struct {
	//EntityInfo data stored as parallel arrays
	EntityIds       []int64  // Entity IDs for each EntityInfo
	CompoundOffsets []int32  // Offset into CompoundData for each EntityInfo's compound
	CompoundLengths []int32  // Length of compound for each EntityInfo
	CompoundData    []uint16 // Flattened compound data (all ComponentIntTypes)
	//SparseArray metadata
	Indices         []int32 // Sparse index mapping
	Idx2Key         []int32 // Dense index to key mapping
	MaxKey          int64   // Maximum key value
	ShrinkThreshold int32   // Shrink threshold
	InitSize        int32   // Initial size
	IsKOrder        bool    // Is key-ordered
}

// NewSerializableEntitySetData creates a new SerializableEntitySetData instance
func NewSerializableEntitySetData() *SerializableEntitySetData {
	return &SerializableEntitySetData{}
}

// PacketIdentifier returns the unique identifier for SerializableEntitySetData
func (x *SerializableEntitySetData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableEntitySetData
}

// Reset resets all fields to their default values
func (x *SerializableEntitySetData) Reset() {
	x.Read((*SerializableEntitySetDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableEntitySetData as root object to the writer
func (x *SerializableEntitySetData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableEntitySetData to the writer at the specified offset
func (x *SerializableEntitySetData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(117)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__EntityIdsSize := uint(8 * len(x.EntityIds))
	__EntityIdsCap := __EntityIdsSize
	__EntityIdsOffset, err := writer.Alloc(__EntityIdsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4+0, uint32(__EntityIdsOffset))
	writer.Write4At(offset+4+4, uint32(__EntityIdsSize))
	writer.Write4At(offset+4+8, uint32(__EntityIdsCap))
	writer.Write4At(offset+4+12, uint32(8))
	if len(x.EntityIds) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice EntityIds: len=%d, size=%d\n", len(x.EntityIds), __EntityIdsSize)
		}
		writer.WriteAt(__EntityIdsOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.EntityIds[0])), __EntityIdsSize))
	}
	__CompoundOffsetsSize := uint(4 * len(x.CompoundOffsets))
	__CompoundOffsetsCap := __CompoundOffsetsSize
	__CompoundOffsetsOffset, err := writer.Alloc(__CompoundOffsetsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+20+0, uint32(__CompoundOffsetsOffset))
	writer.Write4At(offset+20+4, uint32(__CompoundOffsetsSize))
	writer.Write4At(offset+20+8, uint32(__CompoundOffsetsCap))
	writer.Write4At(offset+20+12, uint32(4))
	if len(x.CompoundOffsets) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice CompoundOffsets: len=%d, size=%d\n", len(x.CompoundOffsets), __CompoundOffsetsSize)
		}
		writer.WriteAt(__CompoundOffsetsOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.CompoundOffsets[0])), __CompoundOffsetsSize))
	}
	__CompoundLengthsSize := uint(4 * len(x.CompoundLengths))
	__CompoundLengthsCap := __CompoundLengthsSize
	__CompoundLengthsOffset, err := writer.Alloc(__CompoundLengthsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+36+0, uint32(__CompoundLengthsOffset))
	writer.Write4At(offset+36+4, uint32(__CompoundLengthsSize))
	writer.Write4At(offset+36+8, uint32(__CompoundLengthsCap))
	writer.Write4At(offset+36+12, uint32(4))
	if len(x.CompoundLengths) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice CompoundLengths: len=%d, size=%d\n", len(x.CompoundLengths), __CompoundLengthsSize)
		}
		writer.WriteAt(__CompoundLengthsOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.CompoundLengths[0])), __CompoundLengthsSize))
	}
	__CompoundDataSize := uint(2 * len(x.CompoundData))
	__CompoundDataCap := __CompoundDataSize
	__CompoundDataOffset, err := writer.Alloc(__CompoundDataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+52+0, uint32(__CompoundDataOffset))
	writer.Write4At(offset+52+4, uint32(__CompoundDataSize))
	writer.Write4At(offset+52+8, uint32(__CompoundDataCap))
	writer.Write4At(offset+52+12, uint32(2))
	if len(x.CompoundData) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice CompoundData: len=%d, size=%d\n", len(x.CompoundData), __CompoundDataSize)
		}
		writer.WriteAt(__CompoundDataOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.CompoundData[0])), __CompoundDataSize))
	}
	__IndicesSize := uint(4 * len(x.Indices))
	__IndicesCap := __IndicesSize
	__IndicesOffset, err := writer.Alloc(__IndicesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+68+0, uint32(__IndicesOffset))
	writer.Write4At(offset+68+4, uint32(__IndicesSize))
	writer.Write4At(offset+68+8, uint32(__IndicesCap))
	writer.Write4At(offset+68+12, uint32(4))
	if len(x.Indices) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Indices: len=%d, size=%d\n", len(x.Indices), __IndicesSize)
		}
		writer.WriteAt(__IndicesOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Indices[0])), __IndicesSize))
	}
	__Idx2KeySize := uint(4 * len(x.Idx2Key))
	__Idx2KeyCap := __Idx2KeySize
	__Idx2KeyOffset, err := writer.Alloc(__Idx2KeySize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+84+0, uint32(__Idx2KeyOffset))
	writer.Write4At(offset+84+4, uint32(__Idx2KeySize))
	writer.Write4At(offset+84+8, uint32(__Idx2KeyCap))
	writer.Write4At(offset+84+12, uint32(4))
	if len(x.Idx2Key) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Idx2Key: len=%d, size=%d\n", len(x.Idx2Key), __Idx2KeySize)
		}
		writer.WriteAt(__Idx2KeyOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Idx2Key[0])), __Idx2KeySize))
	}
	__MaxKeyOffset := offset + 100
	writer.Write8At(__MaxKeyOffset, *(*uint64)(unsafe.Pointer(&x.MaxKey)))
	__ShrinkThresholdOffset := offset + 108
	writer.Write4At(__ShrinkThresholdOffset, *(*uint32)(unsafe.Pointer(&x.ShrinkThreshold)))
	__InitSizeOffset := offset + 112
	writer.Write4At(__InitSizeOffset, *(*uint32)(unsafe.Pointer(&x.InitSize)))
	__IsKOrderOffset := offset + 116
	writer.Write1At(__IsKOrderOffset, *(*uint8)(unsafe.Pointer(&x.IsKOrder)))

	return offset, nil
}

// WriteDefault writes the SerializableEntitySetData default value to the writer at the specified offset
func (x *SerializableEntitySetData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(117)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *SerializableEntitySetData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableEntitySetDataViewer(reader, 0), reader)
}

func (x *SerializableEntitySetData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableEntitySetDataViewer(reader, offset), reader)
}

func (x *SerializableEntitySetData) Read(viewer *SerializableEntitySetDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.EntityIds = viewer.EntityIds(reader)
	x.CompoundOffsets = viewer.CompoundOffsets(reader)
	x.CompoundLengths = viewer.CompoundLengths(reader)
	x.CompoundData = viewer.CompoundData(reader)
	x.Indices = viewer.Indices(reader)
	x.Idx2Key = viewer.Idx2Key(reader)
	x.MaxKey = viewer.MaxKey()
	x.ShrinkThreshold = viewer.ShrinkThreshold()
	x.InitSize = viewer.InitSize()
	x.IsKOrder = viewer.IsKOrder()
}

// SerializableEntityIDGeneratorData EntityIDGenerator serializable data structure
// SerializableEntityIDGeneratorData Used for serializing ID generator state for proper ID allocation after restore
type SerializableEntityIDGeneratorData struct {
	Ids         []int64 // All ReuseID data (index and reuse packed as int64)
	Free        int32   // Next free index
	Pending     int32   // Pending allocation index
	Len         int32   // Current entity count
	RemoveDelay []int64 // Delayed removal queue (ReuseID packed as int64)
	DelayFree   int32   // Number of delayed free entries
	DelayCap    int32   // Capacity of delayed removal queue
}

// NewSerializableEntityIDGeneratorData creates a new SerializableEntityIDGeneratorData instance
func NewSerializableEntityIDGeneratorData() *SerializableEntityIDGeneratorData {
	return &SerializableEntityIDGeneratorData{}
}

// PacketIdentifier returns the unique identifier for SerializableEntityIDGeneratorData
func (x *SerializableEntityIDGeneratorData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableEntityIDGeneratorData
}

// Reset resets all fields to their default values
func (x *SerializableEntityIDGeneratorData) Reset() {
	x.Read((*SerializableEntityIDGeneratorDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableEntityIDGeneratorData as root object to the writer
func (x *SerializableEntityIDGeneratorData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableEntityIDGeneratorData to the writer at the specified offset
func (x *SerializableEntityIDGeneratorData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(56)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__IdsSize := uint(8 * len(x.Ids))
	__IdsCap := __IdsSize
	__IdsOffset, err := writer.Alloc(__IdsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4+0, uint32(__IdsOffset))
	writer.Write4At(offset+4+4, uint32(__IdsSize))
	writer.Write4At(offset+4+8, uint32(__IdsCap))
	writer.Write4At(offset+4+12, uint32(8))
	if len(x.Ids) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice Ids: len=%d, size=%d\n", len(x.Ids), __IdsSize)
		}
		writer.WriteAt(__IdsOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Ids[0])), __IdsSize))
	}
	__FreeOffset := offset + 20
	writer.Write4At(__FreeOffset, *(*uint32)(unsafe.Pointer(&x.Free)))
	__PendingOffset := offset + 24
	writer.Write4At(__PendingOffset, *(*uint32)(unsafe.Pointer(&x.Pending)))
	__LenOffset := offset + 28
	writer.Write4At(__LenOffset, *(*uint32)(unsafe.Pointer(&x.Len)))
	__RemoveDelaySize := uint(8 * len(x.RemoveDelay))
	__RemoveDelayCap := __RemoveDelaySize
	__RemoveDelayOffset, err := writer.Alloc(__RemoveDelaySize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+32+0, uint32(__RemoveDelayOffset))
	writer.Write4At(offset+32+4, uint32(__RemoveDelaySize))
	writer.Write4At(offset+32+8, uint32(__RemoveDelayCap))
	writer.Write4At(offset+32+12, uint32(8))
	if len(x.RemoveDelay) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice RemoveDelay: len=%d, size=%d\n", len(x.RemoveDelay), __RemoveDelaySize)
		}
		writer.WriteAt(__RemoveDelayOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.RemoveDelay[0])), __RemoveDelaySize))
	}
	__DelayFreeOffset := offset + 48
	writer.Write4At(__DelayFreeOffset, *(*uint32)(unsafe.Pointer(&x.DelayFree)))
	__DelayCapOffset := offset + 52
	writer.Write4At(__DelayCapOffset, *(*uint32)(unsafe.Pointer(&x.DelayCap)))

	return offset, nil
}

// WriteDefault writes the SerializableEntityIDGeneratorData default value to the writer at the specified offset
func (x *SerializableEntityIDGeneratorData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(56)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *SerializableEntityIDGeneratorData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableEntityIDGeneratorDataViewer(reader, 0), reader)
}

func (x *SerializableEntityIDGeneratorData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableEntityIDGeneratorDataViewer(reader, offset), reader)
}

func (x *SerializableEntityIDGeneratorData) Read(viewer *SerializableEntityIDGeneratorDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.Ids = viewer.Ids(reader)
	x.Free = viewer.Free()
	x.Pending = viewer.Pending()
	x.Len = viewer.Len()
	x.RemoveDelay = viewer.RemoveDelay(reader)
	x.DelayFree = viewer.DelayFree()
	x.DelayCap = viewer.DelayCap()
}

// SerializableComponentSetEntry ComponentSetEntry serializable data structure
// SerializableComponentSetEntry Used for serializing a single component set with its type identifier
type SerializableComponentSetEntry struct {
	ComponentType uint16                      // Component type identifier
	Data          SerializableSparseArrayData // Component set data
	_             [2]byte                     // padding for 8-byte alignment
}

// NewSerializableComponentSetEntry creates a new SerializableComponentSetEntry instance
func NewSerializableComponentSetEntry() *SerializableComponentSetEntry {
	return &SerializableComponentSetEntry{}
}

// PacketIdentifier returns the unique identifier for SerializableComponentSetEntry
func (x *SerializableComponentSetEntry) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableComponentSetEntry
}

// Reset resets all fields to their default values
func (x *SerializableComponentSetEntry) Reset() {
	x.Read((*SerializableComponentSetEntryViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableComponentSetEntry as root object to the writer
func (x *SerializableComponentSetEntry) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableComponentSetEntry to the writer at the specified offset
func (x *SerializableComponentSetEntry) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(8)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__ComponentTypeOffset := offset + 0
	writer.Write2At(__ComponentTypeOffset, *(*uint16)(unsafe.Pointer(&x.ComponentType)))
	__DataSize := uint(57)
	__DataOffset, err := writer.Alloc(__DataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+2, uint32(__DataOffset))
	if _, err := x.Data.Write(writer, __DataOffset); err != nil {
		return offset, err
	}

	return offset, nil
}

// WriteDefault writes the SerializableComponentSetEntry default value to the writer at the specified offset
func (x *SerializableComponentSetEntry) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(8)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__DataSize := uint(57)
	__DataOffset, err := writer.Alloc(__DataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+2, uint32(__DataOffset))
	if _, err := x.Data.WriteDefault(writer, __DataOffset); err != nil {
		return offset, err
	}

	return offset, nil
}

func (x *SerializableComponentSetEntry) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableComponentSetEntryViewer(reader, 0), reader)
}

func (x *SerializableComponentSetEntry) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableComponentSetEntryViewer(reader, offset), reader)
}

func (x *SerializableComponentSetEntry) Read(viewer *SerializableComponentSetEntryViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.ComponentType = viewer.ComponentType()
	x.Data.Read(viewer.Data(reader), reader)
}

// SerializableWorldData World serializable data structure
// SerializableWorldData Complete state of a World that can be serialized for migration
type SerializableWorldData struct {
	//Core entity data
	Entities    SerializableEntitySetData         // All entities with their compounds
	IdGenerator SerializableEntityIDGeneratorData // ID generator state
	//Component data - stored as array of entries
	ComponentSets []SerializableComponentSetEntry // All component sets
	//World runtime state
	Frame           uint64   // Current frame number
	DisposableTypes []uint16 // Disposable component types
	NomadicTypes    []uint16 // Nomadic component types
}

// NewSerializableWorldData creates a new SerializableWorldData instance
func NewSerializableWorldData() *SerializableWorldData {
	return &SerializableWorldData{}
}

// PacketIdentifier returns the unique identifier for SerializableWorldData
func (x *SerializableWorldData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableWorldData
}

// Reset resets all fields to their default values
func (x *SerializableWorldData) Reset() {
	x.Read((*SerializableWorldDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableWorldData as root object to the writer
func (x *SerializableWorldData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableWorldData to the writer at the specified offset
func (x *SerializableWorldData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(64)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__EntitiesSize := uint(117)
	__EntitiesOffset, err := writer.Alloc(__EntitiesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4, uint32(__EntitiesOffset))
	if _, err := x.Entities.Write(writer, __EntitiesOffset); err != nil {
		return offset, err
	}
	__IdGeneratorSize := uint(56)
	__IdGeneratorOffset, err := writer.Alloc(__IdGeneratorSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+8, uint32(__IdGeneratorOffset))
	if _, err := x.IdGenerator.Write(writer, __IdGeneratorOffset); err != nil {
		return offset, err
	}
	__ComponentSetsSize := uint(8 * len(x.ComponentSets))
	__ComponentSetsOffset, err := writer.Alloc(__ComponentSetsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+12, uint32(__ComponentSetsOffset))
	writer.Write4At(offset+12+4, uint32(__ComponentSetsSize))
	writer.Write4At(offset+12+4+4, 8)
	for i := range x.ComponentSets {
		if _, err := x.ComponentSets[i].Write(writer, __ComponentSetsOffset); err != nil {
			return offset, err
		}
		__ComponentSetsOffset += 8
	}
	__FrameOffset := offset + 24
	writer.Write8At(__FrameOffset, *(*uint64)(unsafe.Pointer(&x.Frame)))
	__DisposableTypesSize := uint(2 * len(x.DisposableTypes))
	__DisposableTypesCap := __DisposableTypesSize
	__DisposableTypesOffset, err := writer.Alloc(__DisposableTypesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+32+0, uint32(__DisposableTypesOffset))
	writer.Write4At(offset+32+4, uint32(__DisposableTypesSize))
	writer.Write4At(offset+32+8, uint32(__DisposableTypesCap))
	writer.Write4At(offset+32+12, uint32(2))
	if len(x.DisposableTypes) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice DisposableTypes: len=%d, size=%d\n", len(x.DisposableTypes), __DisposableTypesSize)
		}
		writer.WriteAt(__DisposableTypesOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.DisposableTypes[0])), __DisposableTypesSize))
	}
	__NomadicTypesSize := uint(2 * len(x.NomadicTypes))
	__NomadicTypesCap := __NomadicTypesSize
	__NomadicTypesOffset, err := writer.Alloc(__NomadicTypesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+48+0, uint32(__NomadicTypesOffset))
	writer.Write4At(offset+48+4, uint32(__NomadicTypesSize))
	writer.Write4At(offset+48+8, uint32(__NomadicTypesCap))
	writer.Write4At(offset+48+12, uint32(2))
	if len(x.NomadicTypes) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice NomadicTypes: len=%d, size=%d\n", len(x.NomadicTypes), __NomadicTypesSize)
		}
		writer.WriteAt(__NomadicTypesOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.NomadicTypes[0])), __NomadicTypesSize))
	}

	return offset, nil
}

// WriteDefault writes the SerializableWorldData default value to the writer at the specified offset
func (x *SerializableWorldData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(64)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__EntitiesSize := uint(117)
	__EntitiesOffset, err := writer.Alloc(__EntitiesSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+4, uint32(__EntitiesOffset))
	if _, err := x.Entities.WriteDefault(writer, __EntitiesOffset); err != nil {
		return offset, err
	}
	__IdGeneratorSize := uint(56)
	__IdGeneratorOffset, err := writer.Alloc(__IdGeneratorSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+8, uint32(__IdGeneratorOffset))
	if _, err := x.IdGenerator.WriteDefault(writer, __IdGeneratorOffset); err != nil {
		return offset, err
	}
	__ComponentSetsSize := uint(8 * len(x.ComponentSets))
	__ComponentSetsOffset, err := writer.Alloc(__ComponentSetsSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+12, uint32(__ComponentSetsOffset))
	writer.Write4At(offset+12+4, uint32(__ComponentSetsSize))
	writer.Write4At(offset+12+4+4, 8)

	return offset, nil
}

func (x *SerializableWorldData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableWorldDataViewer(reader, 0), reader)
}

func (x *SerializableWorldData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableWorldDataViewer(reader, offset), reader)
}

func (x *SerializableWorldData) Read(viewer *SerializableWorldDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.Entities.Read(viewer.Entities(reader), reader)
	x.IdGenerator.Read(viewer.IdGenerator(reader), reader)
	__ComponentSetsViewerSlice := viewer.ComponentSets(reader)
	if len(__ComponentSetsViewerSlice) > 0 {
		x.ComponentSets = make([]SerializableComponentSetEntry, len(__ComponentSetsViewerSlice))
		for i := range x.ComponentSets {
			x.ComponentSets[i].Read(&__ComponentSetsViewerSlice[i], reader)
		}
	}
	x.Frame = viewer.Frame()
	x.DisposableTypes = viewer.DisposableTypes(reader)
	x.NomadicTypes = viewer.NomadicTypes(reader)
}

type SerializableUSetDataViewer [44]byte

func NewSerializableUSetDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableUSetDataViewer) {
	if !reader.IsValidOffset(offset, 44) {
		return (*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableUSetDataViewer)(unsafe.Add(reader.Pointer, offset))
	if !reader.IsValidOffset(offset, v.size()) {
		return (*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	return v
}

func (x *SerializableUSetDataViewer) size() uint32 {
	return *(*uint32)(unsafe.Pointer(x))
}

func (x *SerializableUSetDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableUSetDataViewer) EleSize() (v uint64) {
	return *(*uint64)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *SerializableUSetDataViewer) Len() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 12))
}

func (x *SerializableUSetDataViewer) InitSize() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 20))
}

func (x *SerializableUSetDataViewer) Data(reader *rockmem.Reader) (v []byte) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 28))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 28+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []byte{}
	}
	length := uintptr(size / 1)
	return unsafe.Slice((*byte)(unsafe.Add(reader.Pointer, offset)), length)
}

type SerializableSparseArrayDataViewer [57]byte

func NewSerializableSparseArrayDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableSparseArrayDataViewer) {
	if !reader.IsValidOffset(offset, 57) {
		return (*SerializableSparseArrayDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableSparseArrayDataViewer)(unsafe.Add(reader.Pointer, offset))
	if !reader.IsValidOffset(offset, v.size()) {
		return (*SerializableSparseArrayDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	return v
}

func (x *SerializableSparseArrayDataViewer) size() uint32 {
	return *(*uint32)(unsafe.Pointer(x))
}

func (x *SerializableSparseArrayDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableSparseArrayDataViewer) USetData(reader *rockmem.Reader) (v *SerializableUSetDataViewer) {
	if 4+4 > x.size() {
		return (*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4))
	return NewSerializableUSetDataViewer(reader, offset)
}

func (x *SerializableSparseArrayDataViewer) Indices(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 8))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 8+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableSparseArrayDataViewer) Idx2Key(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 24))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 24+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableSparseArrayDataViewer) MaxKey() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 40))
}

func (x *SerializableSparseArrayDataViewer) ShrinkThreshold() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 48))
}

func (x *SerializableSparseArrayDataViewer) InitSize() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 52))
}

func (x *SerializableSparseArrayDataViewer) IsKOrder() (v bool) {
	return *(*bool)(unsafe.Add(unsafe.Pointer(x), 56))
}

type SerializableEntitySetDataViewer [117]byte

func NewSerializableEntitySetDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableEntitySetDataViewer) {
	if !reader.IsValidOffset(offset, 117) {
		return (*SerializableEntitySetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableEntitySetDataViewer)(unsafe.Add(reader.Pointer, offset))
	if !reader.IsValidOffset(offset, v.size()) {
		return (*SerializableEntitySetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	return v
}

func (x *SerializableEntitySetDataViewer) size() uint32 {
	return *(*uint32)(unsafe.Pointer(x))
}

func (x *SerializableEntitySetDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableEntitySetDataViewer) EntityIds(reader *rockmem.Reader) (v []int64) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int64{}
	}
	length := uintptr(size / 8)
	return unsafe.Slice((*int64)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) CompoundOffsets(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 20))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 20+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) CompoundLengths(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 36))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 36+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) CompoundData(reader *rockmem.Reader) (v []uint16) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 52))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 52+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []uint16{}
	}
	length := uintptr(size / 2)
	return unsafe.Slice((*uint16)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) Indices(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 68))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 68+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) Idx2Key(reader *rockmem.Reader) (v []int32) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 84))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 84+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int32{}
	}
	length := uintptr(size / 4)
	return unsafe.Slice((*int32)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntitySetDataViewer) MaxKey() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 100))
}

func (x *SerializableEntitySetDataViewer) ShrinkThreshold() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 108))
}

func (x *SerializableEntitySetDataViewer) InitSize() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 112))
}

func (x *SerializableEntitySetDataViewer) IsKOrder() (v bool) {
	return *(*bool)(unsafe.Add(unsafe.Pointer(x), 116))
}

type SerializableEntityIDGeneratorDataViewer [56]byte

func NewSerializableEntityIDGeneratorDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableEntityIDGeneratorDataViewer) {
	if !reader.IsValidOffset(offset, 56) {
		return (*SerializableEntityIDGeneratorDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableEntityIDGeneratorDataViewer)(unsafe.Add(reader.Pointer, offset))
	if !reader.IsValidOffset(offset, v.size()) {
		return (*SerializableEntityIDGeneratorDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	return v
}

func (x *SerializableEntityIDGeneratorDataViewer) size() uint32 {
	return *(*uint32)(unsafe.Pointer(x))
}

func (x *SerializableEntityIDGeneratorDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableEntityIDGeneratorDataViewer) Ids(reader *rockmem.Reader) (v []int64) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int64{}
	}
	length := uintptr(size / 8)
	return unsafe.Slice((*int64)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntityIDGeneratorDataViewer) Free() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 20))
}

func (x *SerializableEntityIDGeneratorDataViewer) Pending() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 24))
}

func (x *SerializableEntityIDGeneratorDataViewer) Len() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 28))
}

func (x *SerializableEntityIDGeneratorDataViewer) RemoveDelay(reader *rockmem.Reader) (v []int64) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 32))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 32+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []int64{}
	}
	length := uintptr(size / 8)
	return unsafe.Slice((*int64)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableEntityIDGeneratorDataViewer) DelayFree() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 48))
}

func (x *SerializableEntityIDGeneratorDataViewer) DelayCap() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 52))
}

type SerializableComponentSetEntryViewer [8]byte

func NewSerializableComponentSetEntryViewer(reader *rockmem.Reader, offset uint32) (v *SerializableComponentSetEntryViewer) {
	if !reader.IsValidOffset(offset, 8) {
		return (*SerializableComponentSetEntryViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableComponentSetEntryViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *SerializableComponentSetEntryViewer) size() uint32 {
	return 8
}

func (x *SerializableComponentSetEntryViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableComponentSetEntryViewer) ComponentType() (v uint16) {
	return *(*uint16)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *SerializableComponentSetEntryViewer) Data(reader *rockmem.Reader) (v *SerializableSparseArrayDataViewer) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 2))
	return NewSerializableSparseArrayDataViewer(reader, offset)
}

type SerializableWorldDataViewer [64]byte

func NewSerializableWorldDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableWorldDataViewer) {
	if !reader.IsValidOffset(offset, 64) {
		return (*SerializableWorldDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableWorldDataViewer)(unsafe.Add(reader.Pointer, offset))
	if !reader.IsValidOffset(offset, v.size()) {
		return (*SerializableWorldDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	return v
}

func (x *SerializableWorldDataViewer) size() uint32 {
	return *(*uint32)(unsafe.Pointer(x))
}

func (x *SerializableWorldDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableWorldDataViewer) Entities(reader *rockmem.Reader) (v *SerializableEntitySetDataViewer) {
	if 4+4 > x.size() {
		return (*SerializableEntitySetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 4))
	return NewSerializableEntitySetDataViewer(reader, offset)
}

func (x *SerializableWorldDataViewer) IdGenerator(reader *rockmem.Reader) (v *SerializableEntityIDGeneratorDataViewer) {
	if 8+4 > x.size() {
		return (*SerializableEntityIDGeneratorDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 8))
	return NewSerializableEntityIDGeneratorDataViewer(reader, offset)
}

func (x *SerializableWorldDataViewer) ComponentSets(reader *rockmem.Reader) (v []SerializableComponentSetEntryViewer) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 12))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 12+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []SerializableComponentSetEntryViewer{}
	}
	length := uintptr(size / 8)
	return unsafe.Slice((*SerializableComponentSetEntryViewer)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableWorldDataViewer) Frame() (v uint64) {
	return *(*uint64)(unsafe.Add(unsafe.Pointer(x), 24))
}

func (x *SerializableWorldDataViewer) DisposableTypes(reader *rockmem.Reader) (v []uint16) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 32))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 32+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []uint16{}
	}
	length := uintptr(size / 2)
	return unsafe.Slice((*uint16)(unsafe.Add(reader.Pointer, offset)), length)
}

func (x *SerializableWorldDataViewer) NomadicTypes(reader *rockmem.Reader) (v []uint16) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 48))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 48+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []uint16{}
	}
	length := uintptr(size / 2)
	return unsafe.Slice((*uint16)(unsafe.Add(reader.Pointer, offset)), length)
}

type SerializableUSetDataModifier struct {
	*SerializableUSetDataViewer
}

func NewSerializableUSetDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableUSetDataModifier) {
	return SerializableUSetDataModifier{NewSerializableUSetDataViewer(reader, offset)}
}

func newSerializableUSetDataModifierByViewer(viewer *SerializableUSetDataViewer) (v SerializableUSetDataModifier) {
	return SerializableUSetDataModifier{viewer}
}

func (x *SerializableUSetDataModifier) SetEleSize(v uint64) {
	*(*uint64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 4)) = v
}

func (x *SerializableUSetDataModifier) SetLen(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 12)) = v
}

func (x *SerializableUSetDataModifier) SetInitSize(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 20)) = v
}

func (x *SerializableUSetDataModifier) SetData(v []byte) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 28+8))
	newSize := 1 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 28+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 28+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

type SerializableSparseArrayDataModifier struct {
	*SerializableSparseArrayDataViewer
}

func NewSerializableSparseArrayDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableSparseArrayDataModifier) {
	return SerializableSparseArrayDataModifier{NewSerializableSparseArrayDataViewer(reader, offset)}
}

func newSerializableSparseArrayDataModifierByViewer(viewer *SerializableSparseArrayDataViewer) (v SerializableSparseArrayDataModifier) {
	return SerializableSparseArrayDataModifier{viewer}
}

func (x *SerializableSparseArrayDataModifier) SetIndices(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 8+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 8+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 8+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableSparseArrayDataModifier) SetIdx2Key(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 24+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 24+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 24+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableSparseArrayDataModifier) SetMaxKey(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 40)) = v
}

func (x *SerializableSparseArrayDataModifier) SetShrinkThreshold(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 48)) = v
}

func (x *SerializableSparseArrayDataModifier) SetInitSize(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 52)) = v
}

func (x *SerializableSparseArrayDataModifier) SetIsKOrder(v bool) {
	*(*bool)(unsafe.Add(unsafe.Pointer(x.SerializableSparseArrayDataViewer), 56)) = v
}

type SerializableEntitySetDataModifier struct {
	*SerializableEntitySetDataViewer
}

func NewSerializableEntitySetDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableEntitySetDataModifier) {
	return SerializableEntitySetDataModifier{NewSerializableEntitySetDataViewer(reader, offset)}
}

func newSerializableEntitySetDataModifierByViewer(viewer *SerializableEntitySetDataViewer) (v SerializableEntitySetDataModifier) {
	return SerializableEntitySetDataModifier{viewer}
}

func (x *SerializableEntitySetDataModifier) SetEntityIds(v []int64) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 4+8))
	newSize := 8 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 4+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 4+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetCompoundOffsets(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 20+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 20+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 20+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetCompoundLengths(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 36+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 36+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 36+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetCompoundData(v []uint16) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 52+8))
	newSize := 2 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 52+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 52+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetIndices(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 68+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 68+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 68+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetIdx2Key(v []int32) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 84+8))
	newSize := 4 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 84+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 84+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntitySetDataModifier) SetMaxKey(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 100)) = v
}

func (x *SerializableEntitySetDataModifier) SetShrinkThreshold(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 108)) = v
}

func (x *SerializableEntitySetDataModifier) SetInitSize(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 112)) = v
}

func (x *SerializableEntitySetDataModifier) SetIsKOrder(v bool) {
	*(*bool)(unsafe.Add(unsafe.Pointer(x.SerializableEntitySetDataViewer), 116)) = v
}

type SerializableEntityIDGeneratorDataModifier struct {
	*SerializableEntityIDGeneratorDataViewer
}

func NewSerializableEntityIDGeneratorDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableEntityIDGeneratorDataModifier) {
	return SerializableEntityIDGeneratorDataModifier{NewSerializableEntityIDGeneratorDataViewer(reader, offset)}
}

func newSerializableEntityIDGeneratorDataModifierByViewer(viewer *SerializableEntityIDGeneratorDataViewer) (v SerializableEntityIDGeneratorDataModifier) {
	return SerializableEntityIDGeneratorDataModifier{viewer}
}

func (x *SerializableEntityIDGeneratorDataModifier) SetIds(v []int64) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 4+8))
	newSize := 8 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 4+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 4+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntityIDGeneratorDataModifier) SetFree(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 20)) = v
}

func (x *SerializableEntityIDGeneratorDataModifier) SetPending(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 24)) = v
}

func (x *SerializableEntityIDGeneratorDataModifier) SetLen(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 28)) = v
}

func (x *SerializableEntityIDGeneratorDataModifier) SetRemoveDelay(v []int64) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 32+8))
	newSize := 8 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 32+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 32+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableEntityIDGeneratorDataModifier) SetDelayFree(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 48)) = v
}

func (x *SerializableEntityIDGeneratorDataModifier) SetDelayCap(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.SerializableEntityIDGeneratorDataViewer), 52)) = v
}

type SerializableComponentSetEntryModifier struct {
	*SerializableComponentSetEntryViewer
}

func NewSerializableComponentSetEntryModifier(reader *rockmem.Reader, offset uint32) (v SerializableComponentSetEntryModifier) {
	return SerializableComponentSetEntryModifier{NewSerializableComponentSetEntryViewer(reader, offset)}
}

func newSerializableComponentSetEntryModifierByViewer(viewer *SerializableComponentSetEntryViewer) (v SerializableComponentSetEntryModifier) {
	return SerializableComponentSetEntryModifier{viewer}
}

func (x *SerializableComponentSetEntryModifier) SetComponentType(v uint16) {
	*(*uint16)(unsafe.Add(unsafe.Pointer(x.SerializableComponentSetEntryViewer), 0)) = v
}

type SerializableWorldDataModifier struct {
	*SerializableWorldDataViewer
}

func NewSerializableWorldDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableWorldDataModifier) {
	return SerializableWorldDataModifier{NewSerializableWorldDataViewer(reader, offset)}
}

func newSerializableWorldDataModifierByViewer(viewer *SerializableWorldDataViewer) (v SerializableWorldDataModifier) {
	return SerializableWorldDataModifier{viewer}
}

func (x *SerializableWorldDataModifier) SetFrame(v uint64) {
	*(*uint64)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 24)) = v
}

func (x *SerializableWorldDataModifier) SetDisposableTypes(v []uint16) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 32+8))
	newSize := 2 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 32+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 32+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}

func (x *SerializableWorldDataModifier) SetNomadicTypes(v []uint16) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 48+8))
	newSize := 2 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 48+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), 48+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableWorldDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}
