// Code generated by RockMem. DO NOT EDIT.
package ecs

import (
	"errors"
	"fmt"
	rockmem "github.com/zllangct/rockmem/golang"
	"unsafe"
)

var _ unsafe.Pointer
var _ = errors.New("")
var _ fmt.State

var _Null_ecs = [40]byte{}
var _NullReader_ecs = rockmem.NewReader(_Null_ecs[:])

func init() {
}

const (
	PacketIdentifierSerializableUSetData = 14494556342195307757
)

type SerializableUSetData struct {
	EleSize  uint64
	Len      int64
	InitSize int64
	Data     []byte
}

// NewSerializableUSetData creates a new SerializableUSetData instance
func NewSerializableUSetData() *SerializableUSetData {
	return &SerializableUSetData{}
}

// PacketIdentifier returns the unique identifier for SerializableUSetData
func (x *SerializableUSetData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierSerializableUSetData
}

// Reset resets all fields to their default values
func (x *SerializableUSetData) Reset() {
	x.Read((*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0])), _NullReader_ecs)
}

// WriteAsRoot writes the SerializableUSetData as root object to the writer
func (x *SerializableUSetData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the SerializableUSetData to the writer at the specified offset
func (x *SerializableUSetData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(40)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__eleSizeOffset := offset + 0
	writer.Write8At(__eleSizeOffset, *(*uint64)(unsafe.Pointer(&x.EleSize)))
	__lenOffset := offset + 8
	writer.Write8At(__lenOffset, *(*uint64)(unsafe.Pointer(&x.Len)))
	__initSizeOffset := offset + 16
	writer.Write8At(__initSizeOffset, *(*uint64)(unsafe.Pointer(&x.InitSize)))
	__dataSize := uint(1 * len(x.Data))
	__dataCap := __dataSize
	__dataOffset, err := writer.Alloc(__dataSize)
	if err != nil {
		return 0, err
	}
	writer.Write4At(offset+24+0, uint32(__dataOffset))
	writer.Write4At(offset+24+4, uint32(__dataSize))
	writer.Write4At(offset+24+8, uint32(__dataCap))
	writer.Write4At(offset+24+12, uint32(1))
	if len(x.Data) > 0 {
		if rockmem.IsDebugEnabled() {
			fmt.Printf("Writing slice data: len=%d, size=%d\n", len(x.Data), __dataSize)
		}
		writer.WriteAt(__dataOffset, unsafe.Slice((*byte)(unsafe.Pointer(&x.Data[0])), __dataSize))
	}

	return offset, nil
}

// WriteDefault writes the SerializableUSetData default value to the writer at the specified offset
func (x *SerializableUSetData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(40)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *SerializableUSetData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewSerializableUSetDataViewer(reader, 0), reader)
}

func (x *SerializableUSetData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewSerializableUSetDataViewer(reader, offset), reader)
}

func (x *SerializableUSetData) Read(viewer *SerializableUSetDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.EleSize = viewer.EleSize()
	x.Len = viewer.Len()
	x.InitSize = viewer.InitSize()
	__DataSlice := viewer.Data(reader)
	__DataLen := len(__DataSlice)
	if __DataLen > cap(x.Data) {
		x.Data = make([]byte, __DataLen)
	} else {
		x.Data = x.Data[:__DataLen]
	}
	copy(x.Data, __DataSlice)
}

type SerializableUSetDataViewer [40]byte

func NewSerializableUSetDataViewer(reader *rockmem.Reader, offset uint32) (v *SerializableUSetDataViewer) {
	if !reader.IsValidOffset(offset, 40) {
		return (*SerializableUSetDataViewer)(unsafe.Pointer(&_Null_ecs[0]))
	}
	v = (*SerializableUSetDataViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *SerializableUSetDataViewer) size() uint32 {
	return 40
}

func (x *SerializableUSetDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *SerializableUSetDataViewer) EleSize() (v uint64) {
	return *(*uint64)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *SerializableUSetDataViewer) Len() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 8))
}

func (x *SerializableUSetDataViewer) InitSize() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 16))
}

func (x *SerializableUSetDataViewer) Data(reader *rockmem.Reader) (v []byte) {
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 24))
	size := *(*uint32)(unsafe.Add(unsafe.Pointer(x), 24+4))
	if !reader.IsValidOffset(uint32(offset), size) {
		return []byte{}
	}
	length := uintptr(size / 1)
	return unsafe.Slice((*byte)(unsafe.Add(reader.Pointer, offset)), length)
}

type SerializableUSetDataModifier struct {
	*SerializableUSetDataViewer
}

func NewSerializableUSetDataModifier(reader *rockmem.Reader, offset uint32) (v SerializableUSetDataModifier) {
	return SerializableUSetDataModifier{NewSerializableUSetDataViewer(reader, offset)}
}

func newSerializableUSetDataModifierByViewer(viewer *SerializableUSetDataViewer) (v SerializableUSetDataModifier) {
	return SerializableUSetDataModifier{viewer}
}

func (x *SerializableUSetDataModifier) SetEleSize(v uint64) {
	*(*uint64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 0)) = v
}

func (x *SerializableUSetDataModifier) SetLen(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 8)) = v
}

func (x *SerializableUSetDataModifier) SetInitSize(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 16)) = v
}

func (x *SerializableUSetDataModifier) SetData(v []byte) error {
	cap := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 24+8))
	newSize := 1 * uint32(len(v))
	if newSize > cap {
		return errors.New("invalid size, new size must less than capacity")
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 24+4)) = newSize
	offset := *(*uint32)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), 24+0))
	srcData := unsafe.Slice((*byte)(unsafe.Pointer(&v[0])), newSize)
	dstData := unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x.SerializableUSetDataViewer), offset)), newSize)
	copy(dstData, srcData)
	return nil
}
