// Code generated by RockMem. DO NOT EDIT.
package components

import (
	"errors"
	"fmt"
	ecs "github.com/zllangct/ecs"
	rockmem "github.com/zllangct/rockmem/golang"
	"unsafe"
)

var _ unsafe.Pointer
var _ = errors.New("")
var _ fmt.State

var _Null_components = [48]byte{}
var _NullReader_components = rockmem.NewReader(_Null_components[:])

func init() {
	ecs.RegisterComponent[Position]("components")
	ecs.RegisterComponent[Velocity]("components")
	ecs.RegisterComponent[Player]("components")
	ecs.RegisterComponent[Health]("components")
	ecs.RegisterComponent[DamageEvent]("components")
}

const (
	PacketIdentifierPosition    = 14274740599321850262
	PacketIdentifierVelocity    = 11902035645857708318
	PacketIdentifierPlayer      = 8232229719869227258
	PacketIdentifierHealth      = 2586536861959540839
	PacketIdentifierDamageEvent = 17512361240650144843
)

// Position Position组件 - 表示实体的位置
type Position struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewPosition creates a new Position instance
func NewPosition() *Position {
	return &Position{}
}

// PacketIdentifier returns the unique identifier for Position
func (x *Position) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierPosition
}

// Reset resets all fields to their default values
func (x *Position) Reset() {
	x.Read((*PositionViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Position as root object to the writer
func (x *Position) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Position to the writer at the specified offset
func (x *Position) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Position default value to the writer at the specified offset
func (x *Position) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Position) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewPositionViewer(reader, 0), reader)
}

func (x *Position) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewPositionViewer(reader, offset), reader)
}

func (x *Position) Read(viewer *PositionViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

// Velocity Velocity组件 - 表示实体的速度
type Velocity struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewVelocity creates a new Velocity instance
func NewVelocity() *Velocity {
	return &Velocity{}
}

// PacketIdentifier returns the unique identifier for Velocity
func (x *Velocity) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierVelocity
}

// Reset resets all fields to their default values
func (x *Velocity) Reset() {
	x.Read((*VelocityViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Velocity as root object to the writer
func (x *Velocity) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Velocity to the writer at the specified offset
func (x *Velocity) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Velocity default value to the writer at the specified offset
func (x *Velocity) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Velocity) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewVelocityViewer(reader, 0), reader)
}

func (x *Velocity) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewVelocityViewer(reader, offset), reader)
}

func (x *Velocity) Read(viewer *VelocityViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

// Player Player组件 - 表示玩家信息
type Player struct {
	Name      [32]byte
	Level     int32
	Health    float32
	MaxHealth float32
	_         [4]byte // padding for 8-byte alignment
}

// NewPlayer creates a new Player instance
func NewPlayer() *Player {
	return &Player{}
}

// PacketIdentifier returns the unique identifier for Player
func (x *Player) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierPlayer
}

// Reset resets all fields to their default values
func (x *Player) Reset() {
	x.Read((*PlayerViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Player as root object to the writer
func (x *Player) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Player to the writer at the specified offset
func (x *Player) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(48)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__nameOffset := offset + 0
	writer.WriteAt(__nameOffset, (*[32]byte)(unsafe.Pointer(&x.Name))[:])
	__levelOffset := offset + 32
	writer.Write4At(__levelOffset, *(*uint32)(unsafe.Pointer(&x.Level)))
	__healthOffset := offset + 36
	writer.Write4At(__healthOffset, *(*uint32)(unsafe.Pointer(&x.Health)))
	__max_healthOffset := offset + 40
	writer.Write4At(__max_healthOffset, *(*uint32)(unsafe.Pointer(&x.MaxHealth)))

	return offset, nil
}

// WriteDefault writes the Player default value to the writer at the specified offset
func (x *Player) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(48)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__nameOffset := offset + 0
	writer.WriteAt(__nameOffset, (*[32]byte)(unsafe.Pointer(&x.Name))[:])

	return offset, nil
}

func (x *Player) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewPlayerViewer(reader, 0), reader)
}

func (x *Player) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewPlayerViewer(reader, offset), reader)
}

func (x *Player) Read(viewer *PlayerViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	__nameViewerArray := viewer.sliceName()
	copy(x.Name[:], __nameViewerArray)
	x.Level = viewer.Level()
	x.Health = viewer.Health()
	x.MaxHealth = viewer.MaxHealth()
}

// Health Health组件 - 表示生命值
type Health struct {
	Current float32
	Max     float32
}

// NewHealth creates a new Health instance
func NewHealth() *Health {
	return &Health{}
}

// PacketIdentifier returns the unique identifier for Health
func (x *Health) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierHealth
}

// Reset resets all fields to their default values
func (x *Health) Reset() {
	x.Read((*HealthViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Health as root object to the writer
func (x *Health) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Health to the writer at the specified offset
func (x *Health) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(8)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__currentOffset := offset + 0
	writer.Write4At(__currentOffset, *(*uint32)(unsafe.Pointer(&x.Current)))
	__maxOffset := offset + 4
	writer.Write4At(__maxOffset, *(*uint32)(unsafe.Pointer(&x.Max)))

	return offset, nil
}

// WriteDefault writes the Health default value to the writer at the specified offset
func (x *Health) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(8)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Health) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewHealthViewer(reader, 0), reader)
}

func (x *Health) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewHealthViewer(reader, offset), reader)
}

func (x *Health) Read(viewer *HealthViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.Current = viewer.Current()
	x.Max = viewer.Max()
}

// DamageEvent DamageEvent组件 - 一次性伤害事件
type DamageEvent struct {
	Damage   float32
	SourceId int64
	TargetId int64
	_        [4]byte // padding for 8-byte alignment
}

// NewDamageEvent creates a new DamageEvent instance
func NewDamageEvent() *DamageEvent {
	return &DamageEvent{}
}

// PacketIdentifier returns the unique identifier for DamageEvent
func (x *DamageEvent) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierDamageEvent
}

// Reset resets all fields to their default values
func (x *DamageEvent) Reset() {
	x.Read((*DamageEventViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the DamageEvent as root object to the writer
func (x *DamageEvent) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the DamageEvent to the writer at the specified offset
func (x *DamageEvent) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(24)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__damageOffset := offset + 0
	writer.Write4At(__damageOffset, *(*uint32)(unsafe.Pointer(&x.Damage)))
	__source_idOffset := offset + 4
	writer.Write8At(__source_idOffset, *(*uint64)(unsafe.Pointer(&x.SourceId)))
	__target_idOffset := offset + 12
	writer.Write8At(__target_idOffset, *(*uint64)(unsafe.Pointer(&x.TargetId)))

	return offset, nil
}

// WriteDefault writes the DamageEvent default value to the writer at the specified offset
func (x *DamageEvent) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(24)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *DamageEvent) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewDamageEventViewer(reader, 0), reader)
}

func (x *DamageEvent) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewDamageEventViewer(reader, offset), reader)
}

func (x *DamageEvent) Read(viewer *DamageEventViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.Damage = viewer.Damage()
	x.SourceId = viewer.SourceId()
	x.TargetId = viewer.TargetId()
}

type PositionViewer [16]byte

func NewPositionViewer(reader *rockmem.Reader, offset uint32) (v *PositionViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*PositionViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*PositionViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *PositionViewer) size() uint32 {
	return 16
}

func (x *PositionViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *PositionViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *PositionViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *PositionViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type VelocityViewer [16]byte

func NewVelocityViewer(reader *rockmem.Reader, offset uint32) (v *VelocityViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*VelocityViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*VelocityViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *VelocityViewer) size() uint32 {
	return 16
}

func (x *VelocityViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *VelocityViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *VelocityViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *VelocityViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type PlayerViewer [48]byte

func NewPlayerViewer(reader *rockmem.Reader, offset uint32) (v *PlayerViewer) {
	if !reader.IsValidOffset(offset, 48) {
		return (*PlayerViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*PlayerViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *PlayerViewer) size() uint32 {
	return 48
}

func (x *PlayerViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *PlayerViewer) Name() (v []byte) {
	if 0+32 > x.size() {
		return []byte{}
	}
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 32)
}

func (x *PlayerViewer) sliceName() (v []byte) {
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 32)
}

func (x *PlayerViewer) Level() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 32))
}

func (x *PlayerViewer) Health() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 36))
}

func (x *PlayerViewer) MaxHealth() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 40))
}

type HealthViewer [8]byte

func NewHealthViewer(reader *rockmem.Reader, offset uint32) (v *HealthViewer) {
	if !reader.IsValidOffset(offset, 8) {
		return (*HealthViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*HealthViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *HealthViewer) size() uint32 {
	return 8
}

func (x *HealthViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *HealthViewer) Current() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *HealthViewer) Max() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

type DamageEventViewer [24]byte

func NewDamageEventViewer(reader *rockmem.Reader, offset uint32) (v *DamageEventViewer) {
	if !reader.IsValidOffset(offset, 24) {
		return (*DamageEventViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*DamageEventViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *DamageEventViewer) size() uint32 {
	return 24
}

func (x *DamageEventViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *DamageEventViewer) Damage() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *DamageEventViewer) SourceId() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *DamageEventViewer) TargetId() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 12))
}

type PositionModifier struct {
	*PositionViewer
}

func NewPositionModifier(reader *rockmem.Reader, offset uint32) (v PositionModifier) {
	return PositionModifier{NewPositionViewer(reader, offset)}
}

func newPositionModifierByViewer(viewer *PositionViewer) (v PositionModifier) {
	return PositionModifier{viewer}
}

func (x *PositionModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 0)) = v
}

func (x *PositionModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 4)) = v
}

func (x *PositionModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 8)) = v
}

type VelocityModifier struct {
	*VelocityViewer
}

func NewVelocityModifier(reader *rockmem.Reader, offset uint32) (v VelocityModifier) {
	return VelocityModifier{NewVelocityViewer(reader, offset)}
}

func newVelocityModifierByViewer(viewer *VelocityViewer) (v VelocityModifier) {
	return VelocityModifier{viewer}
}

func (x *VelocityModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 0)) = v
}

func (x *VelocityModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 4)) = v
}

func (x *VelocityModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 8)) = v
}

type PlayerModifier struct {
	*PlayerViewer
}

func NewPlayerModifier(reader *rockmem.Reader, offset uint32) (v PlayerModifier) {
	return PlayerModifier{NewPlayerViewer(reader, offset)}
}

func newPlayerModifierByViewer(viewer *PlayerViewer) (v PlayerModifier) {
	return PlayerModifier{viewer}
}

func (x *PlayerModifier) SetName(v *[32]byte) {
	if len(v) != 32 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 32, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[32]byte)(unsafe.Add(unsafe.Pointer(x.PlayerViewer), 0)))[:], v[:])
}

func (x *PlayerModifier) SetLevel(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.PlayerViewer), 32)) = v
}

func (x *PlayerModifier) SetHealth(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PlayerViewer), 36)) = v
}

func (x *PlayerModifier) SetMaxHealth(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PlayerViewer), 40)) = v
}

type HealthModifier struct {
	*HealthViewer
}

func NewHealthModifier(reader *rockmem.Reader, offset uint32) (v HealthModifier) {
	return HealthModifier{NewHealthViewer(reader, offset)}
}

func newHealthModifierByViewer(viewer *HealthViewer) (v HealthModifier) {
	return HealthModifier{viewer}
}

func (x *HealthModifier) SetCurrent(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.HealthViewer), 0)) = v
}

func (x *HealthModifier) SetMax(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.HealthViewer), 4)) = v
}

type DamageEventModifier struct {
	*DamageEventViewer
}

func NewDamageEventModifier(reader *rockmem.Reader, offset uint32) (v DamageEventModifier) {
	return DamageEventModifier{NewDamageEventViewer(reader, offset)}
}

func newDamageEventModifierByViewer(viewer *DamageEventViewer) (v DamageEventModifier) {
	return DamageEventModifier{viewer}
}

func (x *DamageEventModifier) SetDamage(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.DamageEventViewer), 0)) = v
}

func (x *DamageEventModifier) SetSourceId(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.DamageEventViewer), 4)) = v
}

func (x *DamageEventModifier) SetTargetId(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.DamageEventViewer), 12)) = v
}

// Component extension for Position

func (x *Position) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Position]()
}

func (x *Position) IsNomadic() bool {
	return false
}

func (x *Position) IsDisposable() bool {
	return false
}

// Component extension for Velocity

func (x *Velocity) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Velocity]()
}

func (x *Velocity) IsNomadic() bool {
	return false
}

func (x *Velocity) IsDisposable() bool {
	return false
}

// Component extension for Player

func (x *Player) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Player]()
}

func (x *Player) IsNomadic() bool {
	return false
}

func (x *Player) IsDisposable() bool {
	return false
}

// String helper methods for Player.Name (marked with @string() tag)

func (x *Player) GetNameString() string {
	// Find the actual string length (excluding trailing zeros)
	n := len(x.Name)
	for n > 0 && x.Name[n-1] == 0 {
		n--
	}
	return string(x.Name[:n])
}

func (x *Player) SetNameString(v string) {
	// Clear the byte array first
	for i := range x.Name {
		x.Name[i] = 0
	}
	// Copy string content, truncate if exceeds capacity
	n := len(v)
	if n > 32 {
		n = 32
	}
	copy(x.Name[:], v[:n])
}

// Component extension for Health

func (x *Health) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Health]()
}

func (x *Health) IsNomadic() bool {
	return false
}

func (x *Health) IsDisposable() bool {
	return false
}

// Component extension for DamageEvent

func (x *DamageEvent) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[DamageEvent]()
}

func (x *DamageEvent) IsNomadic() bool {
	return false
}

func (x *DamageEvent) IsDisposable() bool {
	return true
}
