// Code generated by RockMem. DO NOT EDIT.
package components

import (
	"errors"
	"fmt"
	ecs "github.com/zllangct/ecs"
	rockmem "github.com/zllangct/rockmem/golang"
	"unsafe"
)

var _ unsafe.Pointer
var _ = errors.New("")
var _ fmt.State

var _Null_components = [48]byte{}
var _NullReader_components = rockmem.NewReader(_Null_components[:])

func init() {
	ecs.RegisterComponent[GameState]("components")
	ecs.RegisterComponent[Position]("components")
	ecs.RegisterComponent[Velocity]("components")
	ecs.RegisterComponent[EntityData]("components")
	ecs.RegisterComponent[Inventory]("components")
}

const (
	PacketIdentifierGameState  = 7825894128469208949
	PacketIdentifierPosition   = 14274740599321850262
	PacketIdentifierVelocity   = 11902035645857708318
	PacketIdentifierEntityData = 13352832190958647436
	PacketIdentifierInventory  = 12116236019994833376
)

// GameState GameState组件 - 游戏状态，用于验证序列化
type GameState struct {
	Tick     int64
	Score    int32
	GameName [32]byte
	_        [4]byte // padding for 8-byte alignment
}

// NewGameState creates a new GameState instance
func NewGameState() *GameState {
	return &GameState{}
}

// PacketIdentifier returns the unique identifier for GameState
func (x *GameState) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierGameState
}

// Reset resets all fields to their default values
func (x *GameState) Reset() {
	x.Read((*GameStateViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the GameState as root object to the writer
func (x *GameState) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the GameState to the writer at the specified offset
func (x *GameState) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(48)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__tickOffset := offset + 0
	writer.Write8At(__tickOffset, *(*uint64)(unsafe.Pointer(&x.Tick)))
	__scoreOffset := offset + 8
	writer.Write4At(__scoreOffset, *(*uint32)(unsafe.Pointer(&x.Score)))
	__game_nameOffset := offset + 12
	writer.WriteAt(__game_nameOffset, (*[32]byte)(unsafe.Pointer(&x.GameName))[:])

	return offset, nil
}

// WriteDefault writes the GameState default value to the writer at the specified offset
func (x *GameState) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(48)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__game_nameOffset := offset + 12
	writer.WriteAt(__game_nameOffset, (*[32]byte)(unsafe.Pointer(&x.GameName))[:])

	return offset, nil
}

func (x *GameState) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewGameStateViewer(reader, 0), reader)
}

func (x *GameState) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewGameStateViewer(reader, offset), reader)
}

func (x *GameState) Read(viewer *GameStateViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.Tick = viewer.Tick()
	x.Score = viewer.Score()
	__game_nameViewerArray := viewer.sliceGameName()
	copy(x.GameName[:], __game_nameViewerArray)
}

// Position Position组件 - 实体位置
type Position struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewPosition creates a new Position instance
func NewPosition() *Position {
	return &Position{}
}

// PacketIdentifier returns the unique identifier for Position
func (x *Position) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierPosition
}

// Reset resets all fields to their default values
func (x *Position) Reset() {
	x.Read((*PositionViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Position as root object to the writer
func (x *Position) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Position to the writer at the specified offset
func (x *Position) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Position default value to the writer at the specified offset
func (x *Position) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Position) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewPositionViewer(reader, 0), reader)
}

func (x *Position) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewPositionViewer(reader, offset), reader)
}

func (x *Position) Read(viewer *PositionViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

// Velocity Velocity组件 - 实体速度
type Velocity struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewVelocity creates a new Velocity instance
func NewVelocity() *Velocity {
	return &Velocity{}
}

// PacketIdentifier returns the unique identifier for Velocity
func (x *Velocity) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierVelocity
}

// Reset resets all fields to their default values
func (x *Velocity) Reset() {
	x.Read((*VelocityViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Velocity as root object to the writer
func (x *Velocity) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Velocity to the writer at the specified offset
func (x *Velocity) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Velocity default value to the writer at the specified offset
func (x *Velocity) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Velocity) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewVelocityViewer(reader, 0), reader)
}

func (x *Velocity) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewVelocityViewer(reader, offset), reader)
}

func (x *Velocity) Read(viewer *VelocityViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

// EntityData Entity组件 - 实体基本信息
type EntityData struct {
	Name   [16]byte
	TypeId int32
	Flags  uint32
}

// NewEntityData creates a new EntityData instance
func NewEntityData() *EntityData {
	return &EntityData{}
}

// PacketIdentifier returns the unique identifier for EntityData
func (x *EntityData) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierEntityData
}

// Reset resets all fields to their default values
func (x *EntityData) Reset() {
	x.Read((*EntityDataViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the EntityData as root object to the writer
func (x *EntityData) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the EntityData to the writer at the specified offset
func (x *EntityData) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(24)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__nameOffset := offset + 0
	writer.WriteAt(__nameOffset, (*[16]byte)(unsafe.Pointer(&x.Name))[:])
	__type_idOffset := offset + 16
	writer.Write4At(__type_idOffset, *(*uint32)(unsafe.Pointer(&x.TypeId)))
	__flagsOffset := offset + 20
	writer.Write4At(__flagsOffset, *(*uint32)(unsafe.Pointer(&x.Flags)))

	return offset, nil
}

// WriteDefault writes the EntityData default value to the writer at the specified offset
func (x *EntityData) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(24)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__nameOffset := offset + 0
	writer.WriteAt(__nameOffset, (*[16]byte)(unsafe.Pointer(&x.Name))[:])

	return offset, nil
}

func (x *EntityData) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewEntityDataViewer(reader, 0), reader)
}

func (x *EntityData) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewEntityDataViewer(reader, offset), reader)
}

func (x *EntityData) Read(viewer *EntityDataViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	__nameViewerArray := viewer.sliceName()
	copy(x.Name[:], __nameViewerArray)
	x.TypeId = viewer.TypeId()
	x.Flags = viewer.Flags()
}

// Inventory Inventory组件 - 背包（定长数组示例）
type Inventory struct {
	Items [8]int32
	Count int32
	_     [4]byte // padding for 8-byte alignment
}

// NewInventory creates a new Inventory instance
func NewInventory() *Inventory {
	return &Inventory{}
}

// PacketIdentifier returns the unique identifier for Inventory
func (x *Inventory) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierInventory
}

// Reset resets all fields to their default values
func (x *Inventory) Reset() {
	x.Read((*InventoryViewer)(unsafe.Pointer(&_Null_components[0])), _NullReader_components)
}

// WriteAsRoot writes the Inventory as root object to the writer
func (x *Inventory) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Inventory to the writer at the specified offset
func (x *Inventory) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(40)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__itemsOffset := offset + 0
	writer.WriteAt(__itemsOffset, (*[32]byte)(unsafe.Pointer(&x.Items))[:])
	__countOffset := offset + 32
	writer.Write4At(__countOffset, *(*uint32)(unsafe.Pointer(&x.Count)))

	return offset, nil
}

// WriteDefault writes the Inventory default value to the writer at the specified offset
func (x *Inventory) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(40)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__itemsOffset := offset + 0
	writer.WriteAt(__itemsOffset, (*[32]byte)(unsafe.Pointer(&x.Items))[:])

	return offset, nil
}

func (x *Inventory) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewInventoryViewer(reader, 0), reader)
}

func (x *Inventory) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewInventoryViewer(reader, offset), reader)
}

func (x *Inventory) Read(viewer *InventoryViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	__itemsViewerArray := viewer.sliceItems()
	copy(x.Items[:], __itemsViewerArray)
	x.Count = viewer.Count()
}

type GameStateViewer [48]byte

func NewGameStateViewer(reader *rockmem.Reader, offset uint32) (v *GameStateViewer) {
	if !reader.IsValidOffset(offset, 48) {
		return (*GameStateViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*GameStateViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *GameStateViewer) size() uint32 {
	return 48
}

func (x *GameStateViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *GameStateViewer) Tick() (v int64) {
	return *(*int64)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *GameStateViewer) Score() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 8))
}

func (x *GameStateViewer) GameName() (v []byte) {
	if 12+32 > x.size() {
		return []byte{}
	}
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 12)), 32)
}

func (x *GameStateViewer) sliceGameName() (v []byte) {
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 12)), 32)
}

type PositionViewer [16]byte

func NewPositionViewer(reader *rockmem.Reader, offset uint32) (v *PositionViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*PositionViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*PositionViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *PositionViewer) size() uint32 {
	return 16
}

func (x *PositionViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *PositionViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *PositionViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *PositionViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type VelocityViewer [16]byte

func NewVelocityViewer(reader *rockmem.Reader, offset uint32) (v *VelocityViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*VelocityViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*VelocityViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *VelocityViewer) size() uint32 {
	return 16
}

func (x *VelocityViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *VelocityViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *VelocityViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *VelocityViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type EntityDataViewer [24]byte

func NewEntityDataViewer(reader *rockmem.Reader, offset uint32) (v *EntityDataViewer) {
	if !reader.IsValidOffset(offset, 24) {
		return (*EntityDataViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*EntityDataViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *EntityDataViewer) size() uint32 {
	return 24
}

func (x *EntityDataViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *EntityDataViewer) Name() (v []byte) {
	if 0+16 > x.size() {
		return []byte{}
	}
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 16)
}

func (x *EntityDataViewer) sliceName() (v []byte) {
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 16)
}

func (x *EntityDataViewer) TypeId() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 16))
}

func (x *EntityDataViewer) Flags() (v uint32) {
	return *(*uint32)(unsafe.Add(unsafe.Pointer(x), 20))
}

type InventoryViewer [40]byte

func NewInventoryViewer(reader *rockmem.Reader, offset uint32) (v *InventoryViewer) {
	if !reader.IsValidOffset(offset, 40) {
		return (*InventoryViewer)(unsafe.Pointer(&_Null_components[0]))
	}
	v = (*InventoryViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *InventoryViewer) size() uint32 {
	return 40
}

func (x *InventoryViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *InventoryViewer) Items() (v []int32) {
	if 0+32 > x.size() {
		return []int32{}
	}
	return unsafe.Slice((*int32)(unsafe.Add(unsafe.Pointer(x), 0)), 8)
}

func (x *InventoryViewer) sliceItems() (v []int32) {
	return unsafe.Slice((*int32)(unsafe.Add(unsafe.Pointer(x), 0)), 8)
}

func (x *InventoryViewer) Count() (v int32) {
	return *(*int32)(unsafe.Add(unsafe.Pointer(x), 32))
}

type GameStateModifier struct {
	*GameStateViewer
}

func NewGameStateModifier(reader *rockmem.Reader, offset uint32) (v GameStateModifier) {
	return GameStateModifier{NewGameStateViewer(reader, offset)}
}

func newGameStateModifierByViewer(viewer *GameStateViewer) (v GameStateModifier) {
	return GameStateModifier{viewer}
}

func (x *GameStateModifier) SetTick(v int64) {
	*(*int64)(unsafe.Add(unsafe.Pointer(x.GameStateViewer), 0)) = v
}

func (x *GameStateModifier) SetScore(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.GameStateViewer), 8)) = v
}

func (x *GameStateModifier) SetGameName(v *[32]byte) {
	if len(v) != 32 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 32, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[32]byte)(unsafe.Add(unsafe.Pointer(x.GameStateViewer), 12)))[:], v[:])
}

type PositionModifier struct {
	*PositionViewer
}

func NewPositionModifier(reader *rockmem.Reader, offset uint32) (v PositionModifier) {
	return PositionModifier{NewPositionViewer(reader, offset)}
}

func newPositionModifierByViewer(viewer *PositionViewer) (v PositionModifier) {
	return PositionModifier{viewer}
}

func (x *PositionModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 0)) = v
}

func (x *PositionModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 4)) = v
}

func (x *PositionModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 8)) = v
}

type VelocityModifier struct {
	*VelocityViewer
}

func NewVelocityModifier(reader *rockmem.Reader, offset uint32) (v VelocityModifier) {
	return VelocityModifier{NewVelocityViewer(reader, offset)}
}

func newVelocityModifierByViewer(viewer *VelocityViewer) (v VelocityModifier) {
	return VelocityModifier{viewer}
}

func (x *VelocityModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 0)) = v
}

func (x *VelocityModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 4)) = v
}

func (x *VelocityModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.VelocityViewer), 8)) = v
}

type EntityDataModifier struct {
	*EntityDataViewer
}

func NewEntityDataModifier(reader *rockmem.Reader, offset uint32) (v EntityDataModifier) {
	return EntityDataModifier{NewEntityDataViewer(reader, offset)}
}

func newEntityDataModifierByViewer(viewer *EntityDataViewer) (v EntityDataModifier) {
	return EntityDataModifier{viewer}
}

func (x *EntityDataModifier) SetName(v *[16]byte) {
	if len(v) != 16 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 16, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[16]byte)(unsafe.Add(unsafe.Pointer(x.EntityDataViewer), 0)))[:], v[:])
}

func (x *EntityDataModifier) SetTypeId(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.EntityDataViewer), 16)) = v
}

func (x *EntityDataModifier) SetFlags(v uint32) {
	*(*uint32)(unsafe.Add(unsafe.Pointer(x.EntityDataViewer), 20)) = v
}

type InventoryModifier struct {
	*InventoryViewer
}

func NewInventoryModifier(reader *rockmem.Reader, offset uint32) (v InventoryModifier) {
	return InventoryModifier{NewInventoryViewer(reader, offset)}
}

func newInventoryModifierByViewer(viewer *InventoryViewer) (v InventoryModifier) {
	return InventoryModifier{viewer}
}

func (x *InventoryModifier) SetItems(v *[8]int32) {
	if len(v) != 8 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 8, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[8]int32)(unsafe.Add(unsafe.Pointer(x.InventoryViewer), 0)))[:], v[:])
}

func (x *InventoryModifier) SetCount(v int32) {
	*(*int32)(unsafe.Add(unsafe.Pointer(x.InventoryViewer), 32)) = v
}

// Component extension for GameState

func (x *GameState) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[GameState]()
}

func (x *GameState) IsNomadic() bool {
	return false
}

func (x *GameState) IsDisposable() bool {
	return false
}

// String helper methods for GameState.GameName (marked with @string() tag)

func (x *GameState) GetGameNameString() string {
	// Find the actual string length (excluding trailing zeros)
	n := len(x.GameName)
	for n > 0 && x.GameName[n-1] == 0 {
		n--
	}
	return string(x.GameName[:n])
}

func (x *GameState) SetGameNameString(v string) {
	// Clear the byte array first
	for i := range x.GameName {
		x.GameName[i] = 0
	}
	// Copy string content, truncate if exceeds capacity
	n := len(v)
	if n > 32 {
		n = 32
	}
	copy(x.GameName[:], v[:n])
}

// Component extension for Position

func (x *Position) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Position]()
}

func (x *Position) IsNomadic() bool {
	return false
}

func (x *Position) IsDisposable() bool {
	return false
}

// Component extension for Velocity

func (x *Velocity) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Velocity]()
}

func (x *Velocity) IsNomadic() bool {
	return false
}

func (x *Velocity) IsDisposable() bool {
	return false
}

// Component extension for EntityData

func (x *EntityData) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[EntityData]()
}

func (x *EntityData) IsNomadic() bool {
	return false
}

func (x *EntityData) IsDisposable() bool {
	return false
}

// String helper methods for EntityData.Name (marked with @string() tag)

func (x *EntityData) GetNameString() string {
	// Find the actual string length (excluding trailing zeros)
	n := len(x.Name)
	for n > 0 && x.Name[n-1] == 0 {
		n--
	}
	return string(x.Name[:n])
}

func (x *EntityData) SetNameString(v string) {
	// Clear the byte array first
	for i := range x.Name {
		x.Name[i] = 0
	}
	// Copy string content, truncate if exceeds capacity
	n := len(v)
	if n > 16 {
		n = 16
	}
	copy(x.Name[:], v[:n])
}

// Component extension for Inventory

func (x *Inventory) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Inventory]()
}

func (x *Inventory) IsNomadic() bool {
	return false
}

func (x *Inventory) IsDisposable() bool {
	return false
}
