// Code generated by RockMem. DO NOT EDIT.
package testdata

import (
	"errors"
	"fmt"
	ecs "github.com/zllangct/ecs"
	rockmem "github.com/zllangct/rockmem/golang"
	"unsafe"
)

var _ unsafe.Pointer
var _ = errors.New("")
var _ fmt.State

var _Null_testdata = [56]byte{}
var _NullReader_testdata = rockmem.NewReader(_Null_testdata[:])

func init() {
}

const (
	PacketIdentifierPoint    = 12809409023221035873
	PacketIdentifierPosition = 14274740599321850262
	PacketIdentifierName     = 7328248172266787231
)

type Point struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewPoint creates a new Point instance
func NewPoint() *Point {
	return &Point{}
}

// PacketIdentifier returns the unique identifier for Point
func (x *Point) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierPoint
}

// Reset resets all fields to their default values
func (x *Point) Reset() {
	x.Read((*PointViewer)(unsafe.Pointer(&_Null_testdata[0])), _NullReader_testdata)
}

// WriteAsRoot writes the Point as root object to the writer
func (x *Point) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Point to the writer at the specified offset
func (x *Point) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Point default value to the writer at the specified offset
func (x *Point) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Point) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewPointViewer(reader, 0), reader)
}

func (x *Point) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewPointViewer(reader, offset), reader)
}

func (x *Point) Read(viewer *PointViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

type Position struct {
	X float32
	Y float32
	Z float32
	_ [4]byte // padding for 8-byte alignment
}

// NewPosition creates a new Position instance
func NewPosition() *Position {
	return &Position{}
}

// PacketIdentifier returns the unique identifier for Position
func (x *Position) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierPosition
}

// Reset resets all fields to their default values
func (x *Position) Reset() {
	x.Read((*PositionViewer)(unsafe.Pointer(&_Null_testdata[0])), _NullReader_testdata)
}

// WriteAsRoot writes the Position as root object to the writer
func (x *Position) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Position to the writer at the specified offset
func (x *Position) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__xOffset := offset + 0
	writer.Write4At(__xOffset, *(*uint32)(unsafe.Pointer(&x.X)))
	__yOffset := offset + 4
	writer.Write4At(__yOffset, *(*uint32)(unsafe.Pointer(&x.Y)))
	__zOffset := offset + 8
	writer.Write4At(__zOffset, *(*uint32)(unsafe.Pointer(&x.Z)))

	return offset, nil
}

// WriteDefault writes the Position default value to the writer at the specified offset
func (x *Position) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(16)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))

	return offset, nil
}

func (x *Position) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewPositionViewer(reader, 0), reader)
}

func (x *Position) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewPositionViewer(reader, offset), reader)
}

func (x *Position) Read(viewer *PositionViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	x.X = viewer.X()
	x.Y = viewer.Y()
	x.Z = viewer.Z()
}

type Name struct {
	Value  [16]byte
	Points [2]Point
	Arr    [2]int32
}

// NewName creates a new Name instance
func NewName() *Name {
	return &Name{}
}

// PacketIdentifier returns the unique identifier for Name
func (x *Name) PacketIdentifier() rockmem.PacketIdentifier {
	return PacketIdentifierName
}

// Reset resets all fields to their default values
func (x *Name) Reset() {
	x.Read((*NameViewer)(unsafe.Pointer(&_Null_testdata[0])), _NullReader_testdata)
}

// WriteAsRoot writes the Name as root object to the writer
func (x *Name) WriteAsRoot(writer rockmem.Writer) (offset uint, err error) {
	return x.Write(writer, 0)
}

// Write writes the Name to the writer at the specified offset
func (x *Name) Write(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(56)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	__valueOffset := offset + 0
	writer.WriteAt(__valueOffset, (*[16]byte)(unsafe.Pointer(&x.Value))[:])
	__pointsOffset := offset + 16
	for i := range x.Points {
		if _, err := x.Points[i].Write(writer, __pointsOffset); err != nil {
			return offset, err
		}
		__pointsOffset += 16
	}
	__arrOffset := offset + 48
	writer.WriteAt(__arrOffset, (*[8]byte)(unsafe.Pointer(&x.Arr))[:])

	return offset, nil
}

// WriteDefault writes the Name default value to the writer at the specified offset
func (x *Name) WriteDefault(writer rockmem.Writer, start uint) (offset uint, err error) {
	offset = start
	size := uint(56)
	if offset == 0 {
		offset, err = writer.Alloc(size)
		if err != nil {
			return 0, err
		}
	}

	writer.Write4At(offset, uint32(size))
	__valueOffset := offset + 0
	writer.WriteAt(__valueOffset, (*[16]byte)(unsafe.Pointer(&x.Value))[:])
	__pointsOffset := offset + 16
	for i := range x.Points {
		if _, err := x.Points[i].WriteDefault(writer, __pointsOffset); err != nil {
			return offset, err
		}
		__pointsOffset += 16
	}
	__arrOffset := offset + 48
	writer.WriteAt(__arrOffset, (*[8]byte)(unsafe.Pointer(&x.Arr))[:])

	return offset, nil
}

func (x *Name) ReadAsRoot(reader *rockmem.Reader) {
	x.Read(NewNameViewer(reader, 0), reader)
}

func (x *Name) ReadWithOffset(reader *rockmem.Reader, offset uint32) {
	x.Read(NewNameViewer(reader, offset), reader)
}

func (x *Name) Read(viewer *NameViewer, reader *rockmem.Reader) {
	if viewer == nil {
		return
	}
	__valueViewerArray := viewer.sliceValue()
	copy(x.Value[:], __valueViewerArray)
	__pointsViewerArray := viewer.Points()
	for i := range x.Points {
		x.Points[i].Read(&__pointsViewerArray[i], reader)
	}
	__arrViewerArray := viewer.sliceArr()
	copy(x.Arr[:], __arrViewerArray)
}

type PointViewer [16]byte

func NewPointViewer(reader *rockmem.Reader, offset uint32) (v *PointViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*PointViewer)(unsafe.Pointer(&_Null_testdata[0]))
	}
	v = (*PointViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *PointViewer) size() uint32 {
	return 16
}

func (x *PointViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *PointViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *PointViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *PointViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type PositionViewer [16]byte

func NewPositionViewer(reader *rockmem.Reader, offset uint32) (v *PositionViewer) {
	if !reader.IsValidOffset(offset, 16) {
		return (*PositionViewer)(unsafe.Pointer(&_Null_testdata[0]))
	}
	v = (*PositionViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *PositionViewer) size() uint32 {
	return 16
}

func (x *PositionViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *PositionViewer) X() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 0))
}

func (x *PositionViewer) Y() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 4))
}

func (x *PositionViewer) Z() (v float32) {
	return *(*float32)(unsafe.Add(unsafe.Pointer(x), 8))
}

type NameViewer [56]byte

func NewNameViewer(reader *rockmem.Reader, offset uint32) (v *NameViewer) {
	if !reader.IsValidOffset(offset, 56) {
		return (*NameViewer)(unsafe.Pointer(&_Null_testdata[0]))
	}
	v = (*NameViewer)(unsafe.Add(reader.Pointer, offset))
	return v
}

func (x *NameViewer) size() uint32 {
	return 56
}

func (x *NameViewer) RockmemReader() *rockmem.Reader {
	return rockmem.NewReader(x[:])
}

func (x *NameViewer) Value() (v []byte) {
	if 0+16 > x.size() {
		return []byte{}
	}
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 16)
}

func (x *NameViewer) sliceValue() (v []byte) {
	return unsafe.Slice((*byte)(unsafe.Add(unsafe.Pointer(x), 0)), 16)
}

func (x *NameViewer) Points() (v []PointViewer) {
	if 16+32 > x.size() {
		return []PointViewer{}
	}
	return unsafe.Slice((*PointViewer)(unsafe.Add(unsafe.Pointer(x), 16)), 2)
}

func (x *NameViewer) Arr() (v []int32) {
	if 48+8 > x.size() {
		return []int32{}
	}
	return unsafe.Slice((*int32)(unsafe.Add(unsafe.Pointer(x), 48)), 2)
}

func (x *NameViewer) sliceArr() (v []int32) {
	return unsafe.Slice((*int32)(unsafe.Add(unsafe.Pointer(x), 48)), 2)
}

type PointModifier struct {
	*PointViewer
}

func NewPointModifier(reader *rockmem.Reader, offset uint32) (v PointModifier) {
	return PointModifier{NewPointViewer(reader, offset)}
}

func newPointModifierByViewer(viewer *PointViewer) (v PointModifier) {
	return PointModifier{viewer}
}

func (x *PointModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PointViewer), 0)) = v
}

func (x *PointModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PointViewer), 4)) = v
}

func (x *PointModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PointViewer), 8)) = v
}

type PositionModifier struct {
	*PositionViewer
}

func NewPositionModifier(reader *rockmem.Reader, offset uint32) (v PositionModifier) {
	return PositionModifier{NewPositionViewer(reader, offset)}
}

func newPositionModifierByViewer(viewer *PositionViewer) (v PositionModifier) {
	return PositionModifier{viewer}
}

func (x *PositionModifier) SetX(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 0)) = v
}

func (x *PositionModifier) SetY(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 4)) = v
}

func (x *PositionModifier) SetZ(v float32) {
	*(*float32)(unsafe.Add(unsafe.Pointer(x.PositionViewer), 8)) = v
}

type NameModifier struct {
	*NameViewer
}

func NewNameModifier(reader *rockmem.Reader, offset uint32) (v NameModifier) {
	return NameModifier{NewNameViewer(reader, offset)}
}

func newNameModifierByViewer(viewer *NameViewer) (v NameModifier) {
	return NameModifier{viewer}
}

func (x *NameModifier) SetValue(v *[16]byte) {
	if len(v) != 16 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 16, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[16]byte)(unsafe.Add(unsafe.Pointer(x.NameViewer), 0)))[:], v[:])
}

func (x *NameModifier) SetArr(v *[2]int32) {
	if len(v) != 2 {
		if rockmem.IsDebugEnabled() {
			panic("array length mismatch: expected 2, got " + string(rune(len(v))))
		}
		return
	}
	copy((*(*[2]int32)(unsafe.Add(unsafe.Pointer(x.NameViewer), 48)))[:], v[:])
}

// Component extension for Point

func (x Point) ComponentObjectIdentifier() {}

func (x *Point) GetComponentSeq() int32 {
	return 1
}

func (x *Point) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Point]()
}

func (x *Point) IsNomadic() bool {
	return false
}

func (x *Point) IsDisposable() bool {
	return false
}

// Component extension for Position

func (x Position) ComponentObjectIdentifier() {}

func (x *Position) GetComponentSeq() int32 {
	return 2
}

func (x *Position) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Position]()
}

func (x *Position) IsNomadic() bool {
	return false
}

func (x *Position) IsDisposable() bool {
	return false
}

// Component extension for Name

func (x Name) ComponentObjectIdentifier() {}

func (x *Name) GetComponentSeq() int32 {
	return 3
}

func (x *Name) NewComponentSet() ecs.ComponentSet {
	return ecs.NewCSet[Name]()
}

func (x *Name) IsNomadic() bool {
	return false
}

func (x *Name) IsDisposable() bool {
	return false
}

// String helper methods for Name.Value (marked with @string() tag)

func (x *Name) GetValueString() string {
	// Find the actual string length (excluding trailing zeros)
	n := len(x.Value)
	for n > 0 && x.Value[n-1] == 0 {
		n--
	}
	return string(x.Value[:n])
}

func (x *Name) SetValueString(v string) {
	// Clear the byte array first
	for i := range x.Value {
		x.Value[i] = 0
	}
	// Copy string content, truncate if exceeds capacity
	n := len(v)
	if n > 16 {
		n = 16
	}
	copy(x.Value[:], v[:n])
}
